version: '3.8'
services:
  back:
    build:
      context: './'
    container_name: moki-backend
    ports:
      - '${BACKEND_PORT}:${BACKEND_INNER_PORT}'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: moki-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PW}
      MYSQL_DATABASE: moki
    ports:
      - '${MYSQL_PORT}:${MYSQL_INNER_PORT}'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: